### ISSUE TITLE
.proto缓冲文件你是如何将Server端和Client端做的共享一个文件夹？

### ISSUE THREAD

**Issue by axinno1** [stulzq/BlogDemos#4]
我添加.proto文件时都是单独的在各自的项目中，没有做到像AspNetCoregRpcService与AspNetCoreGrpcClient 都是共用一份.proto文件，而且Protos的文件夹有一个特别的蓝色标志，您时如何做到的请教下，谢谢

**Comment by axinno1** [comment]
右键项目，点击添加-服务引用，添加gRPC 的.proto文件 就可以共享了

**Comment by stulzq** [comment]
博文里面都写了的，不仔细看
